include_guard(GLOBAL)
if(NOT TARGET Metamod::SDK)
    message(FATAL_ERROR "Load Metamod cmake/SDK.cmake before the ASExt SDK.")
endif()
mmfg_angelscript_headers()
if(NOT TARGET ASExt::SDK)
    get_filename_component(asext_root "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
    add_library(mmfg_asext_sdk INTERFACE)
    add_library(ASExt::SDK ALIAS mmfg_asext_sdk)
    target_include_directories(mmfg_asext_sdk INTERFACE "${asext_root}/include")
    target_link_libraries(mmfg_asext_sdk INTERFACE Metamod::SDK AngelScript::Headers)
endif()
